// Generated by https://quicktype.io

/**
 * A more detailed version of a tv show.
 * This detailed version has links to torrents.
 */
export interface Show {
    _id: string;
    imdb_id: string;
    tvdb_id: string;
    title: string;
    year: string;
    slug: string;
    synopsis: string;
    runtime: string;
    country: string;
    network: string;
    air_day: string;
    air_time: string;
    status: string;
    num_seasons: number;
    last_updated: number;
    __v: number;
    episodes: Episode[];
    genres: string[];
    images: Images;
    rating: Rating;
}

interface Episode {
    torrents: { [quality : string]: Torrent };
    watched: Watched;
    first_aired: number;
    date_based: boolean;
    overview: null | string;
    title: string;
    episode: number;
    season: number;
    tvdb_id: number;
}

interface Torrent {
    provider: string;
    peers: number;
    seeds: number;
    url: string;
}

interface Watched {
    watched: boolean;
}

interface Images {
    poster: string;
    fanart: string;
    banner: string;
}

interface Rating {
    percentage: number;
    watching: number;
    votes: number;
    loved: number;
    hated: number;
}
