// Generated by https://quicktype.io

/**
 * This is an array of Movies, parsed from api response
 */
export interface Movies {
    movies: Movie[]
}

/**
 * A movie with details and links to torrents
 */
export interface Movie {
    _id: string;
    imdb_id: string;
    title: string;
    year: string;
    synopsis: string;
    runtime: string;
    released: number;
    trailer: string;
    certification: string;
    genres: string[];
    images: Images;
    rating: Rating;

    // Yikes
    torrents: {
        [language: string]: {
            [quality: string]: Version
        }
    };
}

interface Images {
    poster: string;
    fanart: string;
    banner: string;
}

interface Rating {
    percentage: number;
    watching: number;
    votes: number;
    loved: number;
    hated: number;
}

interface Version {
    url: string;
    seed: number;
    peer: number;
    size: number;
    filesize: string;
    provider: string;
}