export default {
    movie_tv: [
        { value: '', label: 'All' },
        { value: 'action', label: 'Action'},
        { value: 'adventure', label: 'Adventure'},
        { value: 'animation', label: 'Animation'},
        { value: 'comedy', label: 'Comedy'},
        { value: 'crime', label: 'Crime'},
        { value: 'disaster', label: 'Disaster'},
        { value: 'documentary', label: 'Documentary'},
        { value: 'drama', label: 'Drama'},
        { value: 'eastern', label: 'Eastern'},
        { value: 'family', label: 'Family'},
        { value: 'fan-film', label: 'Fan-Film'},
        { value: 'fantasy', label: 'Fantasy'},
        { value: 'film-noir', label: 'Film-Noir'},
        { value: 'history', label: 'History'},
        { value: 'holiday', label: 'Holiday'},
        { value: 'horror', label: 'Horror'},
        { value: 'indie', label: 'Indie'},
        { value: 'music', label: 'Music'},
        { value: 'mystery', label: 'Mystery'},
        { value: 'none', label: 'None'},
        { value: 'road', label: 'Road'},
        { value: 'romance', label: 'Romance'},
        { value: 'science-fiction', label: 'Science-Fiction'},
        { value: 'short', label: 'Short'},
        { value: 'sports', label: 'Sports'},
        { value: 'sporting-event', label: 'Sporting-Event'},
        { value: 'suspense', label: 'Suspense'},
        { value: 'thriller', label: 'Thriller'},
        { value: 'tv-movie', label: 'TV-Movie'},
        { value: 'war', label: 'War'},
        { value: 'western', label: 'Western'}
    ],
    anime: [
        { value: '', label: 'All' },
        { value: 'Action', label: 'Action' },
        { value: 'Adventure', label: 'Adventure' },
        { value: 'Comedy', label: 'Comedy' },
        { value: 'Dementia', label: 'Dementia' },
        { value: 'Demons', label: 'Demons' },
        { value: 'Drama', label: 'Drama' },
        { value: 'Ecchi', label: 'Ecchi' },
        { value: 'Fantasy', label: 'Fantasy' },
        { value: 'Game', label: 'Game' },
        { value: 'Gender Bender', label: 'Gender Bender' },
        { value: 'Gore', label: 'Gore' },
        { value: 'Harem', label: 'Harem' },
        { value: 'Historical', label: 'Historical' },
        { value: 'Horror', label: 'Horror' },
        { value: 'Kids', label: 'Kids' },
        { value: 'Magic', label: 'Magic' },
        { value: 'Mahou Shoujo', label: 'Mahou Shoujo' },
        { value: 'Mahou Shounen', label: 'Mahou Shounen' },
        { value: 'Martial Arts', label: 'Martial Arts' },
        { value: 'Mecha', label: 'Mecha' },
        { value: 'Military', label: 'Military' },
        { value: 'Music', label: 'Music' },
        { value: 'Mystery', label: 'Mystery' },
        { value: 'Parody', label: 'Parody' },
        { value: 'Police', label: 'Police' },
        { value: 'Psychological', label: 'Psychological' },
        { value: 'Racing', label: 'Racing' },
        { value: 'Romance', label: 'Romance' },
        { value: 'Samurai', label: 'Samurai' },
        { value: 'School', label: 'School' },
        { value: 'Sci-Fi', label: 'Sci-Fi' },
        { value: 'Shoujo Ai', label: 'Shoujo Ai' },
        { value: 'Shounen Ai', label: 'Shounen Ai' },
        { value: 'Slice of Life', label: 'Slice of Life' },
        { value: 'Space', label: 'Space' },
        { value: 'Sports', label: 'Sports' },
        { value: 'Super Power', label: 'Super Power' },
        { value: 'Supernatural', label: 'Supernatural' },
        { value: 'Thriller', label: 'Thriller' },
        { value: 'Vampire', label: 'Vampire' },
        { value: 'Yuri', label: 'Yuri' }
    ]
};