// Generated by https://quicktype.io

/**
 * A more detailed version of an anime show.
 * This detailed version has links to torrents.
 */
export interface Show {
    _id: string;
    mal_id: string;
    title: string;
    year: string;
    slug: string;
    synopsis: string;
    runtime: string;
    status: string;
    type: string;
    num_seasons: number;
    last_updated: number;
    __v: number;
    episodes: Episode[];
    genres: string[];
    images: Images;
    rating: Rating;
}

interface Episode {
    tvdb_id: string;
    overview: string;
    episode: string;
    season: string;
    torrents: { [quality : string]: Torrent };
    title: string;
}

interface Torrent {
    provider: string;
    peers: number;
    seeds: number;
    url: string;
}

interface Images {
    poster: string;
    fanart: string;
    banner: string;
}

interface Rating {
    percentage: number;
    watching: number;
    votes: number;
    loved: number;
    hated: number;
}