// Generated by https://quicktype.io

export default interface Status {
    repo: string;
    server: string;
    status: string;
    totalAnimes: number;
    totalMovies: number;
    totalShows: number;
    updated: number;
    uptime: number;
    version: string;
    commit: string;
}